package capability

func integrationSpecs() []Spec {
	return []Spec{
		{ID: IntegrationRTKStatus, Kind: KindQuery, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskNone, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone}, Effects: SemanticEffects{Key: string(IntegrationRTKStatus), ReadOnly: true, Idempotent: true}},
		{ID: IntegrationRTKEnable, Kind: KindMutation, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskState, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone, ControlApproval: true}, Effects: SemanticEffects{Key: string(IntegrationRTKEnable), Idempotent: true}},
		{ID: IntegrationRTKDisable, Kind: KindMutation, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskState, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone, ControlApproval: true}, Effects: SemanticEffects{Key: string(IntegrationRTKDisable), Idempotent: true}},
		{ID: IntegrationRTKProbe, Kind: KindQuery, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskNone, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone}, Effects: SemanticEffects{Key: string(IntegrationRTKProbe), ReadOnly: true, Idempotent: true}},
		{ID: IntegrationRTKInstall, Kind: KindMutation, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskSensitive, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone, ControlApproval: true}, Effects: SemanticEffects{Key: string(IntegrationRTKInstall), OpenWorld: true}},
		{ID: IntegrationCodeGraphStatus, Kind: KindQuery, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskNone, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone}, Effects: SemanticEffects{Key: string(IntegrationCodeGraphStatus), ReadOnly: true, Idempotent: true}},
		{ID: IntegrationCodeGraphProbe, Kind: KindQuery, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskNone, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone}, Effects: SemanticEffects{Key: string(IntegrationCodeGraphProbe), ReadOnly: true, Idempotent: true}},
		{ID: IntegrationCodeGraphInstall, Kind: KindMutation, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskSensitive, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone, ControlApproval: true}, Effects: SemanticEffects{Key: string(IntegrationCodeGraphInstall), OpenWorld: true}},
		{ID: IntegrationCodeGraphWorkspaceStatus, Kind: KindQuery, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskNone, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone}, Effects: SemanticEffects{Key: string(IntegrationCodeGraphWorkspaceStatus), ReadOnly: true, Idempotent: true}},
		{ID: IntegrationCodeGraphWorkspaceInit, Kind: KindMutation, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskState, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone, ControlApproval: true}, Effects: SemanticEffects{Key: string(IntegrationCodeGraphWorkspaceInit), Idempotent: true}},
		{ID: IntegrationCodeGraphWorkspaceSync, Kind: KindMutation, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskState, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone, ControlApproval: true}, Effects: SemanticEffects{Key: string(IntegrationCodeGraphWorkspaceSync), Idempotent: true}},
		{ID: IntegrationTypeSafeStatus, Kind: KindQuery, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskNone, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone}, Effects: SemanticEffects{Key: string(IntegrationTypeSafeStatus), ReadOnly: true, Idempotent: true}, CLI: CLIBinding{CanonicalPath: "integration typesafe status"}},
		{ID: IntegrationTypeSafeEnable, Kind: KindMutation, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskState, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone, ControlApproval: true}, Effects: SemanticEffects{Key: string(IntegrationTypeSafeEnable), Idempotent: true}},
		{ID: IntegrationTypeSafeDisable, Kind: KindMutation, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskState, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone, ControlApproval: true}, Effects: SemanticEffects{Key: string(IntegrationTypeSafeDisable), Idempotent: true}},
		{ID: IntegrationTypeSafeProbe, Kind: KindQuery, Audience: AudienceOperator, Authorization: AuthorizationOperator, Risk: RiskNone, Confirmation: ConfirmationPolicy{Mode: ConfirmationNone}, Effects: SemanticEffects{Key: string(IntegrationTypeSafeProbe), ReadOnly: true, Idempotent: true, OpenWorld: true}, CLI: CLIBinding{CanonicalPath: "integration typesafe probe"}},
	}
}
