import { useEffect, useState } from "react"
import { RefreshCw } from "lucide-react"
import { JsonViewer } from "@/components/json-viewer"
import { PageError, PageLoading } from "@/components/page-state"
import { TextViewer } from "@/components/text-viewer"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Switch } from "@/components/ui/switch"
import { ScrollableTabsList, Tabs, TabsContent, TabsTrigger } from "@/components/ui/tabs"
import { adminApi, type InstructionSource, type ProjectContextResult } from "@/lib/api"

export function WorkspaceContext({ workspaceID }: { workspaceID: string }) {
  const [result, setResult] = useState<ProjectContextResult | null>(null)
  const [path, setPath] = useState("")
  const [includeGit, setIncludeGit] = useState(true)
  const [includeMemory, setIncludeMemory] = useState(true)
  const [includeSkills, setIncludeSkills] = useState(true)
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState("")

  async function load(refresh = false) {
    if (refresh) setBusy(true)
    try { setResult(await adminApi.workspaceContext(workspaceID, { path, include_git: includeGit, include_memory: includeMemory, include_skills: includeSkills })); setError("") } catch (value) { setError(errorText(value)) } finally { setLoading(false); setBusy(false) }
  }
  useEffect(() => { let active = true; void adminApi.workspaceContext(workspaceID, { include_git: true, include_memory: true, include_skills: true }).then((value) => { if (active) { setResult(value); setError("") } }).catch((value) => { if (active) setError(errorText(value)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [workspaceID])

  return <div className="space-y-4"><PageError message={error} /><Card><CardContent className="pt-0"><div className="grid gap-3 lg:grid-cols-[1fr_auto]"><Input aria-label="Project context path" placeholder="Project root or subproject path, e.g. packages/app" value={path} onChange={(event) => setPath(event.target.value)} /><Button disabled={busy} variant="outline" onClick={() => void load(true)}><RefreshCw className={busy ? "animate-spin" : ""} />Preview</Button></div><div className="mt-4 flex flex-wrap gap-5"><ContextToggle label="Git" checked={includeGit} onCheckedChange={setIncludeGit} /><ContextToggle label="Memory" checked={includeMemory} onCheckedChange={setIncludeMemory} /><ContextToggle label="Skills" checked={includeSkills} onCheckedChange={setIncludeSkills} /></div></CardContent></Card>{loading ? <PageLoading rows={5} /> : result ? <><div className="flex flex-wrap gap-2"><Badge variant="secondary">{formatBytes(result.summary.instruction_bytes)} instructions</Badge><Badge variant="outline">{formatBytes(result.summary.memory_bytes)} memory</Badge><Badge variant="outline">{result.summary.rules} rules</Badge><Badge variant="outline">{result.summary.skills} skills</Badge>{result.instruction_context.instruction_truncated ? <Badge variant="destructive">Truncated</Badge> : null}</div><Tabs defaultValue="rendered"><ScrollableTabsList className="justify-start"><TabsTrigger value="rendered">Rendered</TabsTrigger><TabsTrigger value="sources">Sources</TabsTrigger><TabsTrigger value="json">JSON</TabsTrigger></ScrollableTabsList><TabsContent className="mt-4" value="rendered"><TextViewer maxHeight="52rem" value={result.instruction_context.instructions_text} /></TabsContent><TabsContent className="mt-4 space-y-4" value="sources"><DetectedSources values={result.instruction_context.sources} /><MemorySources result={result} /><RuleAndSkillSources result={result} /></TabsContent><TabsContent className="mt-4" value="json"><JsonViewer maxHeight="52rem" value={result} /></TabsContent></Tabs></> : null}</div>
}

function ContextToggle({ label, checked, onCheckedChange }: { label: string; checked: boolean; onCheckedChange: (checked: boolean) => void }) { return <label className="flex items-center gap-2 text-sm"><Switch checked={checked} onCheckedChange={onCheckedChange} /><span>{label}</span></label> }
function DetectedSources({ values }: { values: InstructionSource[] }) { return <Card><CardHeader><CardTitle>User-level sources</CardTitle><CardDescription>Only resources detected on this machine are listed. Disabled resources are detected but excluded from effective context.</CardDescription></CardHeader><CardContent>{values.length === 0 ? <div className="text-sm text-muted-foreground">No user-level context, rules, or skills detected.</div> : <div className="divide-y">{values.map((source) => <div className="flex items-start justify-between gap-4 py-3 first:pt-0 last:pb-0" key={`${source.provider}-${source.kind}`}><div className="min-w-0"><div className="font-medium">{providerLabel(source.provider)} · {source.kind}</div><div className="mt-1 space-y-1">{source.paths.map((path) => <div className="break-all font-mono text-xs text-muted-foreground" key={path}>{path}</div>)}</div></div><Badge variant={!source.enabled ? "outline" : source.loaded ? "secondary" : "outline"}>{!source.enabled ? "Disabled" : source.loaded ? "Included" : "Detected"}</Badge></div>)}</div>}</CardContent></Card> }
function MemorySources({ result }: { result: ProjectContextResult }) { const sections = [...result.instruction_context.project_memory.sections, ...(result.instruction_context.project_memory.imports ?? [])]; if (!sections.length && !result.instruction_context.auto_memory.loaded && !result.instruction_context.global_context) return null; return <Card><CardHeader><CardTitle>Context sources</CardTitle></CardHeader><CardContent className="space-y-4">{result.instruction_context.global_context ? <SourceText title="Managed global context" value={result.instruction_context.global_context} /> : null}{result.instruction_context.auto_memory.loaded && result.instruction_context.auto_memory.content ? <SourceText title="Auto memory" value={result.instruction_context.auto_memory.content} /> : null}{sections.map((section) => <SourceText key={`${section.kind}-${section.path}`} title={`${section.kind} · ${section.path}${section.truncated ? " · truncated" : ""}`} value={section.content} />)}</CardContent></Card> }
function RuleAndSkillSources({ result }: { result: ProjectContextResult }) { const globalRules = result.instruction_context.global_rules ?? []; const rules = result.instruction_context.rules ?? []; const skills = result.instruction_context.skills ?? []; if (!globalRules.length && !rules.length && !skills.length) return null; return <Card><CardHeader><CardTitle>Rules and skills</CardTitle></CardHeader><CardContent className="space-y-4">{globalRules.map((rule) => <SourceText key={rule.path} title={`Global rule · ${rule.path}`} value={rule.content} />)}{rules.map((rule) => <SourceText key={rule.path} title={`Rule · ${rule.path}`} value={rule.content} />)}{skills.length ? <div><div className="mb-2 text-sm font-medium">Skills</div><div className="space-y-2">{skills.map((skill) => <div className="rounded-lg border p-3" key={`${skill.source}-${skill.name}`}><div className="font-mono text-sm font-medium">{skill.name}</div><div className="mt-1 text-sm text-muted-foreground">{skill.description || "No description."}</div>{skill.path ? <div className="mt-1 break-all font-mono text-xs text-muted-foreground">{skill.path}</div> : null}</div>)}</div></div> : null}</CardContent></Card> }
function SourceText({ title, value }: { title: string; value: string }) { return <div className="min-w-0"><div className="mb-2 break-all text-sm font-medium">{title}</div><TextViewer maxHeight="14rem" value={value} /></div> }
function formatBytes(value: number) { return value < 1024 ? `${value} B` : `${(value / 1024).toFixed(value < 10240 ? 1 : 0)} KB` }
function providerLabel(provider: string) { return provider === "agents" ? "Agents" : provider === "claude" ? "Claude" : provider === "claudes" ? "Claudes" : provider === "cursor" ? "Cursor" : provider === "codex" ? "Codex" : provider }
function errorText(value: unknown) { return value instanceof Error ? value.message : String(value) }
