package telegram

import (
	"context"
	"fmt"
	"strings"

	"go.mewis.me/codemcp/internal/application"
	"go.mewis.me/codemcp/internal/capability"
)

func (ui *Interface) approvalExplanationState(ctx context.Context, requestID string) (application.ApprovalExplainStatus, application.ApprovalExplanationResult, error) {
	value, err := ui.dispatch(ctx, capability.RequestExplainStatus, nil)
	if err != nil {
		return application.ApprovalExplainStatus{}, application.ApprovalExplanationResult{}, err
	}
	status, ok := value.(application.ApprovalExplainStatus)
	if !ok {
		return application.ApprovalExplainStatus{}, application.ApprovalExplanationResult{}, fmt.Errorf("approval Explain status returned an unexpected result")
	}
	value, err = ui.dispatch(ctx, capability.RequestExplanationView, application.ApprovalExplanationReadInput{ID: requestID})
	if err != nil {
		return status, application.ApprovalExplanationResult{}, err
	}
	result, ok := value.(application.ApprovalExplanationResult)
	if !ok {
		return status, application.ApprovalExplanationResult{}, fmt.Errorf("approval explanation returned an unexpected result")
	}
	return status, result, nil
}

func approvalExplanationBlocks(status application.ApprovalExplainStatus, result application.ApprovalExplanationResult, stateErr error) []RichBlock {
	if stateErr != nil {
		return []RichBlock{{Kind: RichDetails, Title: "AI explanation · informational", Text: "Explanation state unavailable: " + compactPresentationValue(stateErr.Error())}}
	}
	if !status.Available {
		reason := strings.TrimSpace(status.Reason)
		if reason == "" {
			reason = "Explanation is unavailable for the active LLM provider."
		}
		return []RichBlock{{Kind: RichDetails, Title: "AI explanation · informational", Text: reason}}
	}
	switch result.State {
	case application.ApprovalExplanationPending:
		return []RichBlock{{Kind: RichDetails, Title: "AI explanation · informational", Text: fmt.Sprintf("Generating · attempt %d", result.Attempt)}}
	case application.ApprovalExplanationFailed:
		failure := strings.TrimSpace(result.Failure)
		if failure == "" {
			failure = "Explanation generation failed."
		}
		return []RichBlock{{Kind: RichDetails, Title: "AI explanation · informational", Text: failure}}
	case application.ApprovalExplanationReady:
		if result.Explanation == nil {
			return []RichBlock{{Kind: RichDetails, Title: "AI explanation · informational", Text: "Explanation result is unavailable."}}
		}
		explanation := result.Explanation
		blocks := []RichBlock{{Kind: RichDetails, Title: "AI explanation · informational", Text: explanation.Summary}}
		blocks = appendApprovalExplanationList(blocks, "Steps", explanation.Steps)
		blocks = appendApprovalExplanationList(blocks, "Likely effects", explanation.Effects)
		blocks = appendApprovalExplanationList(blocks, "Risk notes", explanation.RiskNotes)
		blocks = appendApprovalExplanationList(blocks, "Unknowns", explanation.Unknowns)
		meta := strings.TrimSpace(strings.Join([]string{string(explanation.ProviderID), explanation.Model}, " · "))
		if meta != "" {
			blocks = append(blocks, RichBlock{Kind: RichDetails, Title: "AI provenance", Text: "Generated by " + meta + ". AI-generated and fallible; it cannot approve or deny the request."})
		}
		return blocks
	default:
		return []RichBlock{{Kind: RichDetails, Title: "AI explanation · informational", Text: "No AI explanation has been generated."}}
	}
}

func appendApprovalExplanationList(blocks []RichBlock, title string, values []string) []RichBlock {
	items := make([]string, 0, len(values))
	for _, value := range values {
		if value = strings.TrimSpace(value); value != "" {
			items = append(items, value)
		}
	}
	if len(items) == 0 {
		return blocks
	}
	return append(blocks, RichBlock{Kind: RichList, Title: title, Items: items})
}
