package telegram

import (
	"strings"

	"go.mewis.me/codemcp/internal/explain"
)

func aiExplanationBlocks(explanation *explain.Explanation, title, provenanceSuffix string) []RichBlock {
	if explanation == nil {
		return nil
	}
	children := make([]RichBlock, 0, 9)
	if summary := strings.TrimSpace(explanation.Summary); summary != "" {
		children = append(children, RichBlock{Kind: RichSection, Title: "Summary", Text: summary})
	}
	children = appendExplanationSection(children, "Steps", explanation.Steps)
	children = appendExplanationSection(children, "Likely effects", explanation.Effects)
	children = appendExplanationSection(children, "Risk notes", explanation.RiskNotes)
	children = appendExplanationSection(children, "Unknowns", explanation.Unknowns)

	blocks := make([]RichBlock, 0, 2)
	if len(children) > 0 {
		blocks = append(blocks, RichBlock{Kind: RichExpandable, Title: title, Children: children})
	}
	meta := strings.Trim(strings.Join([]string{string(explanation.ProviderID), explanation.Model}, " · "), " ·")
	if meta != "" {
		text := "AI source · Generated by " + meta + ". AI-generated and fallible."
		if suffix := strings.TrimSpace(provenanceSuffix); suffix != "" {
			text += " " + suffix
		}
		blocks = append(blocks, RichBlock{Kind: RichDetails, Text: text})
	}
	return blocks
}

func appendExplanationSection(blocks []RichBlock, title string, values []string) []RichBlock {
	items := make([]string, 0, len(values))
	for _, value := range values {
		if value = strings.TrimSpace(value); value != "" {
			items = append(items, value)
		}
	}
	if len(items) == 0 {
		return blocks
	}
	return append(blocks,
		RichBlock{Kind: RichSection, Title: title},
		RichBlock{Kind: RichList, Items: items},
	)
}

func expandableTextBlock(title, text string) RichBlock {
	return RichBlock{
		Kind:     RichExpandable,
		Title:    title,
		Children: []RichBlock{{Kind: RichDetails, Text: text}},
	}
}
