import { useState } from "react"
import { Eye, EyeOff, KeyRound } from "lucide-react"
import { PageError } from "@/components/page-state"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field"
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupInput } from "@/components/ui/input-group"
import { Spinner } from "@/components/ui/spinner"
import { adminApi, adminToken } from "@/lib/api"

export function LoginPage({ onAuthenticated }: { onAuthenticated: () => void }) {
  const [token, setToken] = useState("")
  const [visible, setVisible] = useState(false)
  const [error, setError] = useState("")
  const [busy, setBusy] = useState(false)

  async function submit(event: React.FormEvent) {
    event.preventDefault()
    setBusy(true)
    adminToken.set(token.trim())
    try { await adminApi.health(); setError(""); onAuthenticated() } catch { adminToken.clear(); setError("Invalid admin token") } finally { setBusy(false) }
  }

  return <main className="flex min-h-screen items-center justify-center bg-muted/30 p-4 sm:p-6"><Card className="w-full max-w-md shadow-sm"><CardHeader className="text-center"><div className="mx-auto mb-2 flex size-10 items-center justify-center rounded-lg bg-primary text-primary-foreground"><KeyRound className="size-5" /></div><CardTitle>CodeMCP</CardTitle><CardDescription>Enter the admin token generated by the CLI.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={submit}><Field><FieldLabel htmlFor="admin-token">Admin token</FieldLabel><InputGroup><InputGroupInput autoComplete="current-password" autoFocus id="admin-token" type={visible ? "text" : "password"} value={token} onChange={(event) => setToken(event.target.value)} /><InputGroupAddon align="inline-end"><InputGroupButton aria-label={visible ? "Hide admin token" : "Show admin token"} size="icon-xs" onClick={() => setVisible((value) => !value)}>{visible ? <EyeOff /> : <Eye />}</InputGroupButton></InputGroupAddon></InputGroup><FieldDescription>The token stays in session storage and is cleared when this browser session ends.</FieldDescription></Field><PageError message={error} title="Sign in failed" /><Button className="w-full" disabled={busy || !token.trim()} type="submit">{busy ? <Spinner /> : <KeyRound />}{busy ? "Signing in..." : "Sign in"}</Button></form></CardContent></Card></main>
}
