// Code generated by productpresentationgen; DO NOT EDIT.
export const canonicalPresentationContract = {
  "operations": {
    "activity.stream": {
      "operation": "activity.stream",
      "title": "Stream Activity",
      "subject": "Activity",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "activity.view": {
      "operation": "activity.view",
      "title": "View Activity",
      "subject": "Activity",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "auth.admin.disable": {
      "operation": "auth.admin.disable",
      "title": "Disable Admin Auth",
      "subject": "Admin Auth",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "auth.admin.enable": {
      "operation": "auth.admin.enable",
      "title": "Enable Admin Auth",
      "subject": "Admin Auth",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "auth.admin.rotate": {
      "operation": "auth.admin.rotate",
      "title": "Create Admin Auth",
      "subject": "Admin Auth",
      "category": "create",
      "danger": "caution",
      "confirmation": "none",
      "input": "form",
      "secret_policy": "one-time-output",
      "secret_recovery": "rotate the credential again if the one-time value is lost"
    },
    "auth.mcp.disable": {
      "operation": "auth.mcp.disable",
      "title": "Disable MCP Auth",
      "subject": "MCP Auth",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "auth.mcp.enable": {
      "operation": "auth.mcp.enable",
      "title": "Enable MCP Auth",
      "subject": "MCP Auth",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "auth.mcp.rotate": {
      "operation": "auth.mcp.rotate",
      "title": "Create MCP Auth",
      "subject": "MCP Auth",
      "category": "create",
      "danger": "caution",
      "confirmation": "none",
      "input": "form",
      "secret_policy": "one-time-output",
      "secret_recovery": "rotate the credential again if the one-time value is lost"
    },
    "auth.status": {
      "operation": "auth.status",
      "title": "Status Auth",
      "subject": "Auth",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "completion.current": {
      "operation": "completion.current",
      "title": "Current Agent Completion",
      "subject": "Agent Completion",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "completion.doctor": {
      "operation": "completion.doctor",
      "title": "Doctor Agent Completion",
      "subject": "Agent Completion",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "completion.feed": {
      "operation": "completion.feed",
      "title": "Feed Agent Completion",
      "subject": "Agent Completion",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "completion.list": {
      "operation": "completion.list",
      "title": "List Agent Completion",
      "subject": "Agent Completion",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "completion.view": {
      "operation": "completion.view",
      "title": "View Agent Completion",
      "subject": "Agent Completion",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "config.export": {
      "operation": "config.export",
      "title": "Export Config",
      "subject": "Config",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "config.get": {
      "operation": "config.get",
      "title": "Get Config",
      "subject": "Config",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "config.import": {
      "operation": "config.import",
      "title": "Import Config",
      "subject": "Config",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "config.init": {
      "operation": "config.init",
      "title": "Init",
      "subject": "Init",
      "category": "create",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "config.list": {
      "operation": "config.list",
      "title": "List Config",
      "subject": "Config",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "config.migrate": {
      "operation": "config.migrate",
      "title": "Migrate Config",
      "subject": "Config",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "config.migrate.secrets": {
      "operation": "config.migrate.secrets",
      "title": "Secrets Config Migrate",
      "subject": "Config Migrate",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "config.patch": {
      "operation": "config.patch",
      "title": "Patch Config",
      "subject": "Config",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "protected-secret",
      "secret_policy": "protected-input",
      "secret_recovery": "replace through protected input; later reads expose configured or masked state only"
    },
    "config.path": {
      "operation": "config.path",
      "title": "Path Config",
      "subject": "Config",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "config.set": {
      "operation": "config.set",
      "title": "Set Config",
      "subject": "Config",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "protected-secret",
      "secret_policy": "protected-input",
      "secret_recovery": "replace through protected input; later reads expose configured or masked state only"
    },
    "config.snapshot.read": {
      "operation": "config.snapshot.read",
      "title": "Snapshot Config",
      "subject": "Config",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "config.uninit": {
      "operation": "config.uninit",
      "title": "Uninit",
      "subject": "Uninit",
      "category": "delete",
      "danger": "destructive",
      "confirmation": "recommended",
      "input": "form"
    },
    "config.verify": {
      "operation": "config.verify",
      "title": "Verify Config",
      "subject": "Config",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "doctor.read": {
      "operation": "doctor.read",
      "title": "Doctor",
      "subject": "Doctor",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "execution.feed": {
      "operation": "execution.feed",
      "title": "Feed Execution",
      "subject": "Execution",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "execution.list": {
      "operation": "execution.list",
      "title": "List Execution",
      "subject": "Execution",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "execution.stream": {
      "operation": "execution.stream",
      "title": "Stream Execution",
      "subject": "Execution",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "execution.view": {
      "operation": "execution.view",
      "title": "View Execution",
      "subject": "Execution",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "health.read": {
      "operation": "health.read",
      "title": "Health",
      "subject": "Health",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "install.run": {
      "operation": "install.run",
      "title": "Install",
      "subject": "Install",
      "category": "create",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "integration.cf.install": {
      "operation": "integration.cf.install",
      "title": "Install Integration CF",
      "subject": "Integration CF",
      "category": "create",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "integration.cf.probe": {
      "operation": "integration.cf.probe",
      "title": "Probe Integration CF",
      "subject": "Integration CF",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "integration.cf.remove": {
      "operation": "integration.cf.remove",
      "title": "Remove Integration CF",
      "subject": "Integration CF",
      "category": "delete",
      "danger": "destructive",
      "confirmation": "required",
      "input": "form"
    },
    "integration.cf.status": {
      "operation": "integration.cf.status",
      "title": "Status Integration CF",
      "subject": "Integration CF",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "integration.cf.update": {
      "operation": "integration.cf.update",
      "title": "Update Integration CF",
      "subject": "Integration CF",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "integration.codegraph.install": {
      "operation": "integration.codegraph.install",
      "title": "Install Integration Codegraph",
      "subject": "Integration Codegraph",
      "category": "create",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "integration.codegraph.install.global": {
      "operation": "integration.codegraph.install.global",
      "title": "Global Integration Codegraph Install",
      "subject": "Integration Codegraph Install",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "integration.codegraph.probe": {
      "operation": "integration.codegraph.probe",
      "title": "Probe Integration Codegraph",
      "subject": "Integration Codegraph",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "integration.codegraph.status": {
      "operation": "integration.codegraph.status",
      "title": "Status Integration Codegraph",
      "subject": "Integration Codegraph",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "integration.codegraph.workspace.init": {
      "operation": "integration.codegraph.workspace.init",
      "title": "Init Integration Codegraph",
      "subject": "Integration Codegraph",
      "category": "create",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "integration.codegraph.workspace.status": {
      "operation": "integration.codegraph.workspace.status",
      "title": "Status Integration Codegraph Workspace",
      "subject": "Integration Codegraph Workspace",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "integration.codegraph.workspace.sync": {
      "operation": "integration.codegraph.workspace.sync",
      "title": "Sync Integration Codegraph",
      "subject": "Integration Codegraph",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "integration.rtk.disable": {
      "operation": "integration.rtk.disable",
      "title": "Disable Integration RTK",
      "subject": "Integration RTK",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "integration.rtk.enable": {
      "operation": "integration.rtk.enable",
      "title": "Enable Integration RTK",
      "subject": "Integration RTK",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "integration.rtk.install": {
      "operation": "integration.rtk.install",
      "title": "Install Integration RTK",
      "subject": "Integration RTK",
      "category": "create",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "integration.rtk.install.global": {
      "operation": "integration.rtk.install.global",
      "title": "Global Integration RTK Install",
      "subject": "Integration RTK Install",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "integration.rtk.probe": {
      "operation": "integration.rtk.probe",
      "title": "Probe Integration RTK",
      "subject": "Integration RTK",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "integration.rtk.status": {
      "operation": "integration.rtk.status",
      "title": "Status Integration RTK",
      "subject": "Integration RTK",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "integration.typesafe.disable": {
      "operation": "integration.typesafe.disable",
      "title": "Disable Integration Typesafe",
      "subject": "Integration Typesafe",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "integration.typesafe.doctor": {
      "operation": "integration.typesafe.doctor",
      "title": "Doctor Integration Typesafe",
      "subject": "Integration Typesafe",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "integration.typesafe.enable": {
      "operation": "integration.typesafe.enable",
      "title": "Enable Integration Typesafe",
      "subject": "Integration Typesafe",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "integration.typesafe.probe": {
      "operation": "integration.typesafe.probe",
      "title": "Probe Integration Typesafe",
      "subject": "Integration Typesafe",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "integration.typesafe.status": {
      "operation": "integration.typesafe.status",
      "title": "Status Integration Typesafe",
      "subject": "Integration Typesafe",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "llm.provider.add": {
      "operation": "llm.provider.add",
      "title": "Add LLM Provider",
      "subject": "LLM Provider",
      "category": "create",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "llm.provider.configure": {
      "operation": "llm.provider.configure",
      "title": "Configure LLM Provider",
      "subject": "LLM Provider",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "llm.provider.credential.clear": {
      "operation": "llm.provider.credential.clear",
      "title": "Clear LLM Provider Key",
      "subject": "LLM Provider Key",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "llm.provider.credential.set": {
      "operation": "llm.provider.credential.set",
      "title": "Set LLM Provider Key",
      "subject": "LLM Provider Key",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "protected-secret",
      "secret_policy": "protected-input",
      "secret_recovery": "replace through protected input; later reads expose configured or masked state only"
    },
    "llm.provider.get": {
      "operation": "llm.provider.get",
      "title": "Show LLM Provider",
      "subject": "LLM Provider",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "llm.provider.list": {
      "operation": "llm.provider.list",
      "title": "List LLM Provider",
      "subject": "LLM Provider",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "llm.provider.models": {
      "operation": "llm.provider.models",
      "title": "Models LLM",
      "subject": "LLM",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "llm.provider.probe": {
      "operation": "llm.provider.probe",
      "title": "Probe LLM",
      "subject": "LLM",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "llm.provider.remove": {
      "operation": "llm.provider.remove",
      "title": "Remove LLM Provider",
      "subject": "LLM Provider",
      "category": "delete",
      "danger": "destructive",
      "confirmation": "required",
      "input": "form"
    },
    "llm.provider.select": {
      "operation": "llm.provider.select",
      "title": "Use LLM",
      "subject": "LLM",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "llm.status": {
      "operation": "llm.status",
      "title": "Status LLM",
      "subject": "LLM",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "logs.clear": {
      "operation": "logs.clear",
      "title": "Clear Logs",
      "subject": "Logs",
      "category": "delete",
      "danger": "destructive",
      "confirmation": "recommended",
      "input": "form"
    },
    "logs.follow": {
      "operation": "logs.follow",
      "title": "Follow Logs",
      "subject": "Logs",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "logs.path": {
      "operation": "logs.path",
      "title": "Path Logs",
      "subject": "Logs",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "logs.read": {
      "operation": "logs.read",
      "title": "Logs",
      "subject": "Logs",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "mcp.http": {
      "operation": "mcp.http",
      "title": "HTTP MCP",
      "subject": "MCP",
      "category": "run",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "mcp.stdio": {
      "operation": "mcp.stdio",
      "title": "Stdio MCP",
      "subject": "MCP",
      "category": "run",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "network.interfaces.list": {
      "operation": "network.interfaces.list",
      "title": "Interfaces Network",
      "subject": "Network",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "notification.status": {
      "operation": "notification.status",
      "title": "Status Notification",
      "subject": "Notification",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "process.clear": {
      "operation": "process.clear",
      "title": "Clear Process",
      "subject": "Process",
      "category": "delete",
      "danger": "destructive",
      "confirmation": "recommended",
      "input": "form"
    },
    "process.list": {
      "operation": "process.list",
      "title": "List Process",
      "subject": "Process",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "process.view": {
      "operation": "process.view",
      "title": "View Process",
      "subject": "Process",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "project.context.read": {
      "operation": "project.context.read",
      "title": "Context Workspace",
      "subject": "Workspace",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "prompt.create": {
      "operation": "prompt.create",
      "title": "Create Prompt",
      "subject": "Prompt",
      "category": "create",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "prompt.delete": {
      "operation": "prompt.delete",
      "title": "Delete Prompt",
      "subject": "Prompt",
      "category": "delete",
      "danger": "destructive",
      "confirmation": "recommended",
      "input": "form"
    },
    "prompt.get": {
      "operation": "prompt.get",
      "title": "Get Prompt",
      "subject": "Prompt",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "prompt.list": {
      "operation": "prompt.list",
      "title": "List Prompt",
      "subject": "Prompt",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "prompt.update": {
      "operation": "prompt.update",
      "title": "Update Prompt",
      "subject": "Prompt",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "request.approve": {
      "operation": "request.approve",
      "title": "Approve Request",
      "subject": "Request",
      "category": "review",
      "danger": "caution",
      "confirmation": "review-decision",
      "input": "decision"
    },
    "request.deny": {
      "operation": "request.deny",
      "title": "Deny Request",
      "subject": "Request",
      "category": "review",
      "danger": "caution",
      "confirmation": "review-decision",
      "input": "decision"
    },
    "request.explain": {
      "operation": "request.explain",
      "title": "Explain Request",
      "subject": "Request",
      "category": "review",
      "danger": "caution",
      "confirmation": "none",
      "input": "decision"
    },
    "request.explain.status": {
      "operation": "request.explain.status",
      "title": "Status Request Explain",
      "subject": "Request Explain",
      "category": "review",
      "danger": "none",
      "confirmation": "none",
      "input": "decision"
    },
    "request.explanation.view": {
      "operation": "request.explanation.view",
      "title": "View Request Explain",
      "subject": "Request Explain",
      "category": "review",
      "danger": "none",
      "confirmation": "none",
      "input": "decision"
    },
    "request.grant.list": {
      "operation": "request.grant.list",
      "title": "List Request Grant",
      "subject": "Request Grant",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "request.grant.revoke": {
      "operation": "request.grant.revoke",
      "title": "Revoke Request Grant",
      "subject": "Request Grant",
      "category": "review",
      "danger": "destructive",
      "confirmation": "review-decision",
      "input": "decision"
    },
    "request.list": {
      "operation": "request.list",
      "title": "List Request",
      "subject": "Request",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "request.stream": {
      "operation": "request.stream",
      "title": "Stream Request",
      "subject": "Request",
      "category": "review",
      "danger": "none",
      "confirmation": "none",
      "input": "decision"
    },
    "request.view": {
      "operation": "request.view",
      "title": "View Request",
      "subject": "Request",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "runtime.down": {
      "operation": "runtime.down",
      "title": "Down",
      "subject": "Down",
      "category": "run",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "runtime.restart": {
      "operation": "runtime.restart",
      "title": "Restart",
      "subject": "Restart",
      "category": "run",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "runtime.up": {
      "operation": "runtime.up",
      "title": "Up",
      "subject": "Up",
      "category": "run",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "server.foreground": {
      "operation": "server.foreground",
      "title": "Serve",
      "subject": "Serve",
      "category": "run",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "status.overview": {
      "operation": "status.overview",
      "title": "Status",
      "subject": "Status",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "telegram.setup": {
      "operation": "telegram.setup",
      "title": "Setup Telegram",
      "subject": "Telegram",
      "category": "create",
      "danger": "caution",
      "confirmation": "none",
      "input": "protected-secret",
      "secret_policy": "protected-input",
      "secret_recovery": "replace through protected input; later reads expose configured or masked state only"
    },
    "telemetry.disable": {
      "operation": "telemetry.disable",
      "title": "Disable Telemetry",
      "subject": "Telemetry",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "telemetry.enable": {
      "operation": "telemetry.enable",
      "title": "Enable Telemetry",
      "subject": "Telemetry",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "telemetry.show": {
      "operation": "telemetry.show",
      "title": "Show Telemetry",
      "subject": "Telemetry",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "telemetry.status": {
      "operation": "telemetry.status",
      "title": "Status Telemetry",
      "subject": "Telemetry",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "tools.inventory.read": {
      "operation": "tools.inventory.read",
      "title": "List Tools",
      "subject": "Tools",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "tunnel.admin.key.remove": {
      "operation": "tunnel.admin.key.remove",
      "title": "Remove Tunnel Admin Key",
      "subject": "Tunnel Admin Key",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "tunnel.admin.key.set": {
      "operation": "tunnel.admin.key.set",
      "title": "Set Tunnel Admin Key",
      "subject": "Tunnel Admin Key",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "protected-secret",
      "secret_policy": "protected-input",
      "secret_recovery": "replace through protected input; later reads expose configured or masked state only"
    },
    "tunnel.admin.key.status": {
      "operation": "tunnel.admin.key.status",
      "title": "Status Tunnel Admin Key",
      "subject": "Tunnel Admin Key",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "tunnel.admin.key.verify": {
      "operation": "tunnel.admin.key.verify",
      "title": "Verify Tunnel Admin Key",
      "subject": "Tunnel Admin Key",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "tunnel.config.read": {
      "operation": "tunnel.config.read",
      "title": "Config Tunnel",
      "subject": "Tunnel",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "tunnel.configure": {
      "operation": "tunnel.configure",
      "title": "Configure Tunnel",
      "subject": "Tunnel",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "protected-secret",
      "secret_policy": "protected-input",
      "secret_recovery": "replace through protected input; later reads expose configured or masked state only"
    },
    "tunnel.create": {
      "operation": "tunnel.create",
      "title": "Create Tunnel",
      "subject": "Tunnel",
      "category": "create",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "tunnel.delete": {
      "operation": "tunnel.delete",
      "title": "Delete Tunnel",
      "subject": "Tunnel",
      "category": "delete",
      "danger": "destructive",
      "confirmation": "required",
      "input": "form"
    },
    "tunnel.disable": {
      "operation": "tunnel.disable",
      "title": "Disable Tunnel",
      "subject": "Tunnel",
      "category": "run",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "tunnel.enable": {
      "operation": "tunnel.enable",
      "title": "Enable Tunnel",
      "subject": "Tunnel",
      "category": "run",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "tunnel.foreground": {
      "operation": "tunnel.foreground",
      "title": "Run Tunnel",
      "subject": "Tunnel",
      "category": "run",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "tunnel.get": {
      "operation": "tunnel.get",
      "title": "Get Tunnel",
      "subject": "Tunnel",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "tunnel.list": {
      "operation": "tunnel.list",
      "title": "List Tunnel",
      "subject": "Tunnel",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "tunnel.status": {
      "operation": "tunnel.status",
      "title": "Status Tunnel",
      "subject": "Tunnel",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "tunnel.sync": {
      "operation": "tunnel.sync",
      "title": "Sync Tunnel",
      "subject": "Tunnel",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "tunnel.update": {
      "operation": "tunnel.update",
      "title": "Update Tunnel",
      "subject": "Tunnel",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "tunnel.use": {
      "operation": "tunnel.use",
      "title": "Use Tunnel",
      "subject": "Tunnel",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "update.apply": {
      "operation": "update.apply",
      "title": "Upgrade",
      "subject": "Upgrade",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "update.check": {
      "operation": "update.check",
      "title": "Check Upgrade",
      "subject": "Upgrade",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "upstream.server.add": {
      "operation": "upstream.server.add",
      "title": "Add Upstream Server",
      "subject": "Upstream Server",
      "category": "create",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "upstream.server.auth.login": {
      "operation": "upstream.server.auth.login",
      "title": "Login Upstream Server Auth",
      "subject": "Upstream Server Auth",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "upstream.server.auth.logout": {
      "operation": "upstream.server.auth.logout",
      "title": "Logout Upstream Server Auth",
      "subject": "Upstream Server Auth",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "upstream.server.auth.status": {
      "operation": "upstream.server.auth.status",
      "title": "Status Upstream Server Auth",
      "subject": "Upstream Server Auth",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "upstream.server.configure": {
      "operation": "upstream.server.configure",
      "title": "Configure Upstream Server",
      "subject": "Upstream Server",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "upstream.server.disable": {
      "operation": "upstream.server.disable",
      "title": "Disable Upstream Server",
      "subject": "Upstream Server",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "upstream.server.enable": {
      "operation": "upstream.server.enable",
      "title": "Enable Upstream Server",
      "subject": "Upstream Server",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "upstream.server.list": {
      "operation": "upstream.server.list",
      "title": "List Upstream Server",
      "subject": "Upstream Server",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "upstream.server.remove": {
      "operation": "upstream.server.remove",
      "title": "Remove Upstream Server",
      "subject": "Upstream Server",
      "category": "delete",
      "danger": "destructive",
      "confirmation": "recommended",
      "input": "form"
    },
    "upstream.server.show": {
      "operation": "upstream.server.show",
      "title": "Show Upstream Server",
      "subject": "Upstream Server",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "upstream.server.status": {
      "operation": "upstream.server.status",
      "title": "Status Upstream Server",
      "subject": "Upstream Server",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "upstream.server.tools": {
      "operation": "upstream.server.tools",
      "title": "Tools Upstream Server",
      "subject": "Upstream Server",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "version.about": {
      "operation": "version.about",
      "title": "Version",
      "subject": "Version",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "workspace.access.add": {
      "operation": "workspace.access.add",
      "title": "Add Workspace Access",
      "subject": "Workspace Access",
      "category": "create",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "workspace.access.list": {
      "operation": "workspace.access.list",
      "title": "List Workspace Access",
      "subject": "Workspace Access",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "workspace.access.remove": {
      "operation": "workspace.access.remove",
      "title": "Remove Workspace Access",
      "subject": "Workspace Access",
      "category": "change",
      "danger": "caution",
      "confirmation": "none",
      "input": "form"
    },
    "workspace.container.add": {
      "operation": "workspace.container.add",
      "title": "Add Workspace Container",
      "subject": "Workspace Container",
      "category": "create",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "workspace.container.create": {
      "operation": "workspace.container.create",
      "title": "Create Workspace Container",
      "subject": "Workspace Container",
      "category": "create",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "workspace.container.delete": {
      "operation": "workspace.container.delete",
      "title": "Delete Workspace Container",
      "subject": "Workspace Container",
      "category": "delete",
      "danger": "destructive",
      "confirmation": "recommended",
      "input": "form"
    },
    "workspace.container.list": {
      "operation": "workspace.container.list",
      "title": "List Workspace Container",
      "subject": "Workspace Container",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "workspace.container.membership.list": {
      "operation": "workspace.container.membership.list",
      "title": "List Workspace Container Membership",
      "subject": "Workspace Container Membership",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "workspace.container.remove": {
      "operation": "workspace.container.remove",
      "title": "Remove Workspace Container",
      "subject": "Workspace Container",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "workspace.container.rename": {
      "operation": "workspace.container.rename",
      "title": "Rename Workspace Container",
      "subject": "Workspace Container",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "workspace.container.show": {
      "operation": "workspace.container.show",
      "title": "Show Workspace Container",
      "subject": "Workspace Container",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "workspace.list": {
      "operation": "workspace.list",
      "title": "List Workspace",
      "subject": "Workspace",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "none"
    },
    "workspace.purge": {
      "operation": "workspace.purge",
      "title": "Purge Workspace",
      "subject": "Workspace",
      "category": "delete",
      "danger": "destructive",
      "confirmation": "required",
      "input": "form"
    },
    "workspace.register": {
      "operation": "workspace.register",
      "title": "Register Workspace",
      "subject": "Workspace",
      "category": "create",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "workspace.relocate": {
      "operation": "workspace.relocate",
      "title": "Relocate Workspace",
      "subject": "Workspace",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    },
    "workspace.show": {
      "operation": "workspace.show",
      "title": "Show Workspace",
      "subject": "Workspace",
      "category": "read",
      "danger": "none",
      "confirmation": "none",
      "input": "resource"
    },
    "workspace.unregister": {
      "operation": "workspace.unregister",
      "title": "Unregister Workspace",
      "subject": "Workspace",
      "category": "change",
      "danger": "none",
      "confirmation": "none",
      "input": "form"
    }
  },
  "lifecycle": {
    "confirming": {
      "state": "confirming",
      "label": "Confirmation required",
      "retryable": false,
      "terminal": false
    },
    "idle": {
      "state": "idle",
      "label": "Ready",
      "retryable": false,
      "terminal": false
    },
    "partial": {
      "state": "partial",
      "label": "Degraded",
      "retryable": false,
      "terminal": true
    },
    "retryable-failure": {
      "state": "retryable-failure",
      "label": "Failed — retry available",
      "retryable": true,
      "terminal": false
    },
    "success": {
      "state": "success",
      "label": "Completed",
      "retryable": false,
      "terminal": true
    },
    "terminal-failure": {
      "state": "terminal-failure",
      "label": "Failed",
      "retryable": false,
      "terminal": true
    },
    "unavailable": {
      "state": "unavailable",
      "label": "Unavailable",
      "retryable": false,
      "terminal": true
    },
    "working": {
      "state": "working",
      "label": "Working",
      "retryable": false,
      "terminal": false
    }
  },
  "navigation": {
    "back": "Back",
    "cancel": "Cancel",
    "close": "Close",
    "home": "Home",
    "refresh": "Refresh",
    "retry": "Retry"
  },
  "timestamp_format": "RFC3339Nano UTC"
} as const
